# Generated by Django 5.0.4 on 2024-04-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('celular', models.CharField(max_length=11)),
                ('pub_date', models.DateTimeField(verbose_name='Date publicada')),
            ],
        ),
    ]
