# Generated by Django 5.0.4 on 2024-05-07 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_agente_supervisor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadastro',
        ),
    ]
