# Generated by Django 5.0.4 on 2024-05-14 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_agente_ativo_supervisor_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agente',
            name='usuario',
        ),
    ]
